### ISSUE TITLE
.idea в репозитории проекта

### ISSUE THREAD

**Issue by chrn-feip** [Vanislavsky/fefu_backend_3_6#2]
Не кладите, пожалуйста, в репозиторий папку .idea. Эта часть вашей локальной среды разработки. Условной команде, которая могла бы работать над проектом, не обязательно знать о этих файлах и пользоваться той же IDE.

**Comment by Vanislavsky** [comment]
Хорошо, могу с помощью git rebase -i убрать

**Comment by chrn-feip** [comment]
Нужно будет убрать, да

**Comment by Vanislavsky** [comment]
Я удалил .idea
